const fs = require('fs');
let content = fs.readFileSync('src/assets/index.js', 'utf8');

const targetRegex = /e\.jsxs\("div",\{style:\{display:"flex",gap:10\},children:\[e\.jsx\("button",\{style:u\(d\(\{\},c\.btn\("s"\)\),\{padding:"10px",fontSize:13,flex:1\}\),onClick:\(\)=>window\.open\("https:\/\/www\.mercadopublico\.cl\/FichaLicitacion\.html\?idLicitacion=" \+ window\.licData\.CodigoExterno, "_blank"\),children:"📄 Ver Bases en MP"\}\),e\.jsx\("button",\{style:u\(d\(\{\},c\.btn\("p"\)\),\{padding:"10px",fontSize:13,flex:2\}\),onClick:\(\)=>\{if\(!window\.licData \|\| !window\.licData\.Items \|\| !window\.licData\.Items\.Listado\) return alert\("Esta licitación no tiene ítems detallados para importar\."\);const nuevoId = n\.nextNum \|\| Date\.now\(\);const items = window\.licData\.Items\.Listado\.map\(\(it, idx\) => \(\{id: "lic_" \+ Date\.now\(\) \+ "_" \+ idx,desc: \(it\.NombreProducto \|\| "Item sin nombre"\)\.substring\(0, 150\),uni: \(it\.UnidadMedida \|\| "un"\)\.substring\(0, 10\),cant: parseFloat\(it\.Cantidad\) \|\| 1,_cid: "", _tipoCosto: "mo", precio: 0, mat: 0, mo: 0, eq: 0, sc: 0\}\)\);const pBase = \{id: nuevoId,fecha: new Date\(\)\.toISOString\(\)\.split\("T"\)\[0\],estado: "Pendiente",clienteId: "",obra: "Licitación " \+ window\.licData\.CodigoExterno,descripcion: window\.licData\.Nombre,items: items,changelog: \[\{fecha: new Date\(\)\.toLocaleString\(\), accion: "Generado desde Licitación " \+ window\.licData\.CodigoExterno\}\]\};if\(setCfg\) setCfg\(me => Object\.assign\(\{\}, me, \{nextNum: nuevoId \+ 1\}\)\);if\(setEditB\) setEditB\(pBase\);if\(setPage\) setPage\("edit"\);\},children:"📋 Crear Presupuesto desde Licitación"\}\)\]\}\)/s;

const replacement = 'e.jsxs("div",{style:{display:"flex",flexDirection:"column",gap:10},children:[e.jsxs("div",{style:{display:"flex",gap:10},children:[e.jsx("button",{style:u(d({},c.btn("s")),{padding:"10px",fontSize:13,flex:1}),onClick:()=>window.open("https://www.mercadopublico.cl/FichaLicitacion.html?idLicitacion=" + window.licData.CodigoExterno, "_blank"),children:"📄 Ver Bases en MP"}),e.jsx("button",{style:u(d({},c.btn("p")),{padding:"10px",fontSize:13,flex:1.5,background:"#2563eb",borderColor:"#1d4ed8"}),onClick:()=>{if(!window.licData) return;if(t.some(x=>x.idMP===window.licData.CodigoExterno)) {return alert("Esta licitación ya está en tu Pipeline.");}const newLic = {id: "lic_" + Date.now(),idMP: window.licData.CodigoExterno,organismo: window.licData.Comprador ? window.licData.Comprador.NombreOrganismo : "",nombreObra: window.licData.Nombre,fechaCierre: window.licData.Fechas ? window.licData.Fechas.FechaCierre : null,descripcion: window.licData.Descripcion,estado: "Borrador",items: window.licData.Items && window.licData.Items.Listado ? window.licData.Items.Listado.map(it => ({id: "it_" + Math.random().toString(36).substring(2, 9),desc: it.NombreProducto || "",uni: it.UnidadMedida || "un",cant: parseFloat(it.Cantidad) || 1,precioNeto: 0,costoMo: 0,costoMat: 0,costoEq: 0})) : []};i([...t, newLic]);if(typeof m === "function") m("✅ Guardada en tu Pipeline. Búscala en \'Detalle\'"); else alert("✅ Guardada en tu Pipeline. Búscala en \'Detalle\'");},children:"📥 Guardar en Pipeline"})]}),e.jsx("button",{style:u(d({},c.btn("p")),{padding:"10px",fontSize:13,width:"100%",background:"#f5a020",color:"#000",border:"none"}),onClick:()=>{if(!window.licData || !window.licData.Items || !window.licData.Items.Listado) return alert("Esta licitación no tiene ítems detallados para importar.");const nuevoId = n.nextNum || Date.now();const items = window.licData.Items.Listado.map((it, idx) => ({id: "lic_" + Date.now() + "_" + idx,desc: (it.NombreProducto || "Item sin nombre").substring(0, 150),uni: (it.UnidadMedida || "un").substring(0, 10),cant: parseFloat(it.Cantidad) || 1,_cid: "", _tipoCosto: "mo", precio: 0, mat: 0, mo: 0, eq: 0, sc: 0}));const pBase = {id: nuevoId,fecha: new Date().toISOString().split("T")[0],estado: "Pendiente",clienteId: "",obra: "Licitación " + window.licData.CodigoExterno,descripcion: window.licData.Nombre,items: items,changelog: [{fecha: new Date().toLocaleString(), accion: "Generado desde Licitación " + window.licData.CodigoExterno}]};if(setCfg) setCfg(me => Object.assign({}, me, {nextNum: nuevoId + 1}));if(setEditB) setEditB(pBase);if(setPage) setPage("edit");},children:"⚡ Presupuestar Directamente"})]})';

if(content.match(targetRegex)) {
    content = content.replace(targetRegex, replacement);
    fs.writeFileSync('src/assets/index.js', content, 'utf8');
    console.log("Replaced buttons successfully!");
} else {
    console.log("Could not find the button block with Regex");
}
