module.exports = [
    {
      id: "bano",
      nombre: "🚿 Remodelación Baño",
      desc: "Baño completo: demolición, revestimientos, artefactos, instalaciones",
      items: [
        {
          desc: "Demolición revestimientos baño",
          cant: 12,
          unidad: "m²",
          _cid: "100",
        },
        { desc: "Estuco interior", cant: 12, unidad: "m²", _cid: "18" },
        {
          desc: "Cerámico muro ducha 30x60cm",
          cant: 8,
          unidad: "m²",
          _cid: "63",
        },
        { desc: "Cerámico piso 45x45cm", cant: 4, unidad: "m²", _cid: "60" },
        {
          desc: "Punto agua PPR (por punto)",
          cant: 4,
          unidad: "unidad",
          _cid: "90",
        },
        {
          desc: "Punto desagüe PVC (por punto)",
          cant: 6,
          unidad: "ml",
          _cid: "161",
        },
        {
          desc: "WC con bidet incluido",
          cant: 1,
          unidad: "unidad",
          _cid: "222",
        },
        {
          desc: "Lavamanos + grifería",
          cant: 1,
          unidad: "unidad",
          _cid: "221",
        },
        {
          desc: "Ducha + grifería termostática",
          cant: 1,
          unidad: "unidad",
          _cid: "220",
        },
        {
          desc: "Punto de luz (foco LED empotrado)",
          cant: 2,
          unidad: "unidad",
          _cid: "80",
        },
        {
          desc: "Pintura cielo baño impermeabilizante",
          cant: 4,
          unidad: "m²",
          _cid: "3",
        },
      ],
    },
    {
      id: "cocina",
      nombre: "🍳 Remodelación Cocina",
      desc: "Cocina completa: revestimientos, instalaciones, muebles",
      items: [
        {
          desc: "Demolición revestimientos cocina",
          cant: 15,
          unidad: "m²",
          _cid: "100",
        },
        { desc: "Estuco interior", cant: 15, unidad: "m²", _cid: "18" },
        { desc: "Cerámico muro cocina", cant: 8, unidad: "m²", _cid: "63" },
        { desc: "Cerámico piso 45x45cm", cant: 12, unidad: "m²", _cid: "60" },
        {
          desc: "Punto agua PPR (por punto)",
          cant: 3,
          unidad: "unidad",
          _cid: "90",
        },
        {
          desc: "Punto desagüe PVC (por punto)",
          cant: 4,
          unidad: "ml",
          _cid: "161",
        },
        {
          desc: "Punto de luz (foco LED empotrado)",
          cant: 4,
          unidad: "unidad",
          _cid: "80",
        },
        {
          desc: "Punto eléctrico toma corriente triple",
          cant: 4,
          unidad: "unidad",
          _cid: "81",
        },
        {
          desc: "Pintura muros interiores (2 manos + sellador)",
          cant: 15,
          unidad: "m²",
          _cid: "1",
        },
      ],
    },
    {
      id: "ampliacion",
      nombre: "🏠 Ampliación Habitación",
      desc: "Ampliación con estructura, cubierta, terminaciones",
      items: [
        { desc: "Radier hormigón H-20", cant: 12, unidad: "m²", _cid: "10" },
        {
          desc: "Muro albañilería reforzada c/bloques",
          cant: 24,
          unidad: "m²",
          _cid: "12",
        },
        {
          desc: "Techumbre cerchas pino + zinc 0.35",
          cant: 20,
          unidad: "m²",
          _cid: "40",
        },
        {
          desc: "Cielo volcanita s/correas pino",
          cant: 20,
          unidad: "m²",
          _cid: "48",
        },
        {
          desc: "Tabique Metalcon 89mm + lana mineral + 1 placa yeso",
          cant: 12,
          unidad: "m²",
          _cid: "22",
        },
        { desc: "Estuco exterior", cant: 24, unidad: "m²", _cid: "17" },
        { desc: "Estuco interior", cant: 36, unidad: "m²", _cid: "18" },
        {
          desc: "Piso flotante laminado AC4",
          cant: 20,
          unidad: "m²",
          _cid: "62",
        },
        {
          desc: "Puerta interior 90x210cm machihembrada",
          cant: 1,
          unidad: "unidad",
          _cid: "70",
        },
        {
          desc: "Pintura muros interiores (2 manos + sellador)",
          cant: 36,
          unidad: "m²",
          _cid: "1",
        },
        {
          desc: "Punto de luz (foco LED empotrado)",
          cant: 3,
          unidad: "unidad",
          _cid: "80",
        },
        {
          desc: "Punto eléctrico toma corriente triple",
          cant: 3,
          unidad: "unidad",
          _cid: "81",
        },
      ],
    },
    {
      id: "techo",
      nombre: "🏚️ Cambio Cubierta / Techo",
      desc: "Retiro cubierta existente y nueva instalación zinc",
      items: [
        {
          desc: "Demolición y retiro cubierta existente",
          cant: 60,
          unidad: "m²",
          _cid: "101",
        },
        {
          desc: "Techumbre cerchas pino + zinc 0.35",
          cant: 60,
          unidad: "m²",
          _cid: "40",
        },
        {
          desc: "Ojalaería y canaletas zinc",
          cant: 24,
          unidad: "ml",
          _cid: "106",
        },
        { desc: "Bajante PVC 100mm", cant: 6, unidad: "ml", _cid: "105" },
      ],
    },
    {
      id: "radier",
      nombre: "🧱 Radier + Pavimento",
      desc: "Radier de hormigón con terminación cerámica o piso flotante",
      items: [
        {
          desc: "Excavación manual fundaciones",
          cant: 3,
          unidad: "m³",
          _cid: "130",
        },
        {
          desc: "Nivelación y compactación terreno (máquina)",
          cant: 20,
          unidad: "m²",
          _cid: "213",
        },
        {
          desc: "Revalses (moldaje contorno radier)",
          cant: 20,
          unidad: "ml",
          _cid: "210",
        },
        {
          desc: "Impermeabilización bajo radier (polietileno)",
          cant: 20,
          unidad: "m²",
          _cid: "212",
        },
        {
          desc: "Enfierradura malla electrosoldada colocada",
          cant: 20,
          unidad: "m²",
          _cid: "211",
        },
        { desc: "Radier hormigón H-20", cant: 20, unidad: "m²", _cid: "10" },
        { desc: "Cerámico piso 45x45cm", cant: 20, unidad: "m²", _cid: "60" },
      ],
    },
    {
      id: "pintura",
      nombre: "🎨 Pintura Completa Interior",
      desc: "Pintura de muros y cielos interior completa",
      items: [
        {
          desc: "Pintura muros interiores (2 manos + sellador)",
          cant: 80,
          unidad: "m²",
          _cid: "1",
        },
        { desc: "Pintura cielos (2 manos)", cant: 40, unidad: "m²" },
        {
          desc: "Pintura puertas y ventanas (esmalte 2 manos)",
          cant: 12,
          unidad: "m²",
          _cid: "4",
        },
      ],
    },
    {
      id: "electrico",
      nombre: "⚡ Instalación Eléctrica",
      desc: "Instalación eléctrica básica domiciliaria",
      items: [
        {
          desc: "Punto de luz (foco LED empotrado)",
          cant: 10,
          unidad: "unidad",
          _cid: "80",
        },
        {
          desc: "Punto eléctrico toma corriente triple",
          cant: 8,
          unidad: "unidad",
          _cid: "81",
        },
        {
          desc: "Punto eléctrico 220V (lavadora/horno)",
          cant: 2,
          unidad: "unidad",
          _cid: "82",
        },
        {
          desc: "Tablero eléctrico 12 circuitos (inst.)",
          cant: 1,
          unidad: "unidad",
          _cid: "83",
        },
        {
          desc: "Cableado principal 4mm² (ml)",
          cant: 20,
          unidad: "ml",
          _cid: "223",
        },
      ],
    },
    {
      id: "cierre",
      nombre: "🔒 Cierre Perimetral",
      desc: "Reja perimetral metálica con fundaciones",
      items: [
        {
          desc: "Reja metálica tubo cuadrado 40x40mm",
          cant: 20,
          unidad: "m²",
          _cid: "120",
        },
        { desc: "Fundación corrida H-20", cant: 0.8, unidad: "m³", _cid: "14" },
        {
          desc: "Pilares tubulares HEB 100 (inst.)",
          cant: 6,
          unidad: "unidad",
          _cid: "123",
        },
        {
          desc: "Puerta metálica 1 hoja 1x2m",
          cant: 1,
          unidad: "unidad",
          _cid: "129",
        },
        {
          desc: "Pintura anticorrosiva + esmalte reja",
          cant: 20,
          unidad: "m²",
          _cid: "5",
        },
      ],
    },
    {
      id: "quincho",
      nombre: "🔥 Quincho / Área Exterior",
      desc: "Quincho con terraza y pavimento exterior",
      items: [
        {
          desc: "Quincho estructura madera (fabricación+inst.)",
          cant: 16,
          unidad: "m²",
          _cid: "196",
        },
        {
          desc: "Cubierta zinc quincho/pérgola",
          cant: 18,
          unidad: "m²",
          _cid: "198",
        },
        {
          desc: "Deck madera tratada exterior",
          cant: 20,
          unidad: "m²",
          _cid: "200",
        },
        {
          desc: "Pavimento adoquín jardín c/base",
          cant: 30,
          unidad: "m²",
          _cid: "203",
        },
        {
          desc: "Iluminación exterior (por punto)",
          cant: 4,
          unidad: "unidad",
          _cid: "209",
        },
      ],
    },
    {
      id: "piscina",
      nombre: "🏊 Piscina Básica",
      desc: "Piscina rectangular con sistema de filtración",
      items: [
        {
          desc: "Excavación piscina (maquinaria)",
          cant: 40,
          unidad: "m³",
          _cid: "187",
        },
        {
          desc: "Estructura hormigón armado piscina H-25",
          cant: 8,
          unidad: "m³",
          _cid: "188",
        },
        {
          desc: "Impermeabilización piscina (membrana)",
          cant: 60,
          unidad: "m²",
          _cid: "189",
        },
        {
          desc: "Revestimiento gresite/cerámico piscina",
          cant: 50,
          unidad: "m²",
          _cid: "190",
        },
        {
          desc: "Sistema filtración + bomba (inst.)",
          cant: 1,
          unidad: "unidad",
          _cid: "191",
        },
        {
          desc: "Escalera acero inoxidable piscina",
          cant: 1,
          unidad: "unidad",
          _cid: "193",
        },
        {
          desc: "Vereda perimetral piscina hormigón",
          cant: 20,
          unidad: "m²",
          _cid: "194",
        },
        {
          desc: "Iluminación subacuática LED (por punto)",
          cant: 2,
          unidad: "unidad",
          _cid: "192",
        },
      ],
    },
  ];